name: docker
on:
  push:
    tags:
    # Check https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
    - '^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v2
    - 
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - 
      name: Install Python Poetry
      uses: abatilo/actions-poetry@v2.1.0
      with:
        poetry-version: 1.1.12
    - 
      name: Configure poetry
      shell: bash
      run: python -m poetry config virtualenvs.in-project true
    - 
      name: View poetry version
      run: poetry --version
    - 
      name: Install dependencies
      run: |
        python -m poetry install
    - 
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Prepare svr build
      run: source build.sh svr
    -
      name: Push svr tag
      uses: docker/build-push-action@v3
      with:
        context: builds/svr
        push: true
        tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/konan-housing-model:${{ github.ref_name }}-svr
    - 
      name: Prepare xgboost build
      run: source build.sh xgboost
    -
      name: Push xgboost tag
      uses: docker/build-push-action@v3
      with:
        context: builds/xgboost
        push: true
        tags: |
          docker.io/${{ secrets.DOCKERHUB_USERNAME }}/konan-housing-model:${{ github.ref_name }}-xgboost
          docker.io/${{ secrets.DOCKERHUB_USERNAME }}/konan-housing-model:latest
